// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using odevweb.Models;

#nullable disable

namespace odevweb.Migrations
{
    [DbContext(typeof(KuaforContext))]
    [Migration("20241215192520_mig_10baglantiveislemekleme")]
    partial class mig_10baglantiveislemekleme
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("odevweb.Models.Islem", b =>
                {
                    b.Property<int>("IslemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IslemId"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sure")
                        .HasColumnType("int");

                    b.Property<double>("Ucret")
                        .HasColumnType("float");

                    b.HasKey("IslemId");

                    b.ToTable("Islems");
                });

            modelBuilder.Entity("odevweb.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanicis");
                });

            modelBuilder.Entity("odevweb.Models.Musteri", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriId"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriId");

                    b.ToTable("Musteris");
                });

            modelBuilder.Entity("odevweb.Models.Personel", b =>
                {
                    b.Property<int>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelId"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IslemId")
                        .HasColumnType("int");

                    b.Property<int>("Uzmanlik")
                        .HasColumnType("int");

                    b.HasKey("PersonelId");

                    b.HasIndex("IslemId");

                    b.ToTable("Personels");
                });

            modelBuilder.Entity("odevweb.Models.PersonelMusaitlik", b =>
                {
                    b.Property<int>("PersonelMusaitlikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelMusaitlikId"), 1L, 1);

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("time");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("PersonelMusaitlikId");

                    b.HasIndex("PersonelId");

                    b.ToTable("PersonelMusaitliks");
                });

            modelBuilder.Entity("odevweb.Models.Randevu", b =>
                {
                    b.Property<int>("RandevuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RandevuId"), 1L, 1);

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Saat")
                        .HasColumnType("time");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<double>("ToplamUcret")
                        .HasColumnType("float");

                    b.HasKey("RandevuId");

                    b.HasIndex("MusteriId");

                    b.ToTable("Randevus");
                });

            modelBuilder.Entity("odevweb.Models.RandevuIslem", b =>
                {
                    b.Property<int>("RandevuId")
                        .HasColumnType("int");

                    b.Property<int>("IslemId")
                        .HasColumnType("int");

                    b.HasKey("RandevuId", "IslemId");

                    b.HasIndex("IslemId");

                    b.ToTable("RandevuIslems");
                });

            modelBuilder.Entity("odevweb.Models.RandevuPersonel", b =>
                {
                    b.Property<int>("RandevuId")
                        .HasColumnType("int");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.HasKey("RandevuId", "PersonelId");

                    b.HasIndex("PersonelId");

                    b.ToTable("RandevuPersonel");
                });

            modelBuilder.Entity("odevweb.Models.Personel", b =>
                {
                    b.HasOne("odevweb.Models.Islem", "Islem")
                        .WithMany("Personels")
                        .HasForeignKey("IslemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Islem");
                });

            modelBuilder.Entity("odevweb.Models.PersonelMusaitlik", b =>
                {
                    b.HasOne("odevweb.Models.Personel", "Personel")
                        .WithMany("PersonelMusaitliks")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("odevweb.Models.Randevu", b =>
                {
                    b.HasOne("odevweb.Models.Musteri", "Musteri")
                        .WithMany("Randevus")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("odevweb.Models.RandevuIslem", b =>
                {
                    b.HasOne("odevweb.Models.Islem", "Islem")
                        .WithMany("Randevus")
                        .HasForeignKey("IslemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("odevweb.Models.Randevu", "Randevu")
                        .WithMany("Islems")
                        .HasForeignKey("RandevuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Islem");

                    b.Navigation("Randevu");
                });

            modelBuilder.Entity("odevweb.Models.RandevuPersonel", b =>
                {
                    b.HasOne("odevweb.Models.Personel", "Personel")
                        .WithMany("Randevus")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("odevweb.Models.Randevu", "Randevu")
                        .WithMany("Personels")
                        .HasForeignKey("RandevuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("Randevu");
                });

            modelBuilder.Entity("odevweb.Models.Islem", b =>
                {
                    b.Navigation("Personels");

                    b.Navigation("Randevus");
                });

            modelBuilder.Entity("odevweb.Models.Musteri", b =>
                {
                    b.Navigation("Randevus");
                });

            modelBuilder.Entity("odevweb.Models.Personel", b =>
                {
                    b.Navigation("PersonelMusaitliks");

                    b.Navigation("Randevus");
                });

            modelBuilder.Entity("odevweb.Models.Randevu", b =>
                {
                    b.Navigation("Islems");

                    b.Navigation("Personels");
                });
#pragma warning restore 612, 618
        }
    }
}
